# Generated by Django 5.2.6 on 2025-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadefiles',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil')], default='CSE', max_length=10),
        ),
        migrations.AddField(
            model_name='uploadefiles',
            name='category',
            field=models.CharField(choices=[('NOTES', 'Notes'), ('ASSIGNMENT', 'Assignment'), ('PRACTICAL', 'Practical')], default='NOTES', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadefiles',
            name='subject',
            field=models.CharField(default='CO', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadefiles',
            name='year',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], default='1', max_length=1),
        ),
    ]
