# Generated by Django 5.2.6 on 2025-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0002_uploadefiles_branch_uploadefiles_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadefiles',
            name='year',
        ),
        migrations.AddField(
            model_name='uploadefiles',
            name='sem',
            field=models.CharField(choices=[('1', 'First SEM'), ('2', 'Second SEM'), ('3', 'Third SEM'), ('4', 'Fourth SEM'), ('5', 'Fifth SEM'), ('6', 'Sixth SEM')], default='1', max_length=1),
        ),
    ]
