# Generated by Django 5.2.6 on 2025-09-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0003_remove_uploadefiles_year_uploadefiles_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadefiles',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics And Communication'), ('ME', 'Mechanical'), ('EE', 'Electronics'), ('CE', 'Civil'), ('FD', 'Fashion')], default='CSE', max_length=10),
        ),
    ]
