# Generated by Django 5.2.6 on 2025-09-25 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='question_papers/')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('single', 'Single Paper'), ('subject', 'All Papers of One Subject'), ('semester', 'All Papers of Semester')], max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('papers', models.ManyToManyField(blank=True, to='User.questionpaper')),
            ],
        ),
    ]
